# Generated by Django 3.1.4 on 2023-02-20 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_lead_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='models',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
