# Generated by Django 3.1.4 on 2023-02-20 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_lead_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='phone',
            field=models.IntegerField(default=0),
        ),
    ]
