# Generated by Django 3.1.4 on 2023-02-20 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_lead_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='models',
            new_name='email',
        ),
    ]
