# Generated by Django 3.1.4 on 2023-02-21 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_auto_20230220_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
