# Generated by Django 3.1.4 on 2023-02-21 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0008_auto_20230221_1929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='age',
        ),
    ]
